spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #空值 不处理
    default-property-inclusion: non_null
    # DataSource Config
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.206.130:3306/security?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true
      connection-timeout: 30000
      max-lifetime: 120000
      connection-test-query: select 1
  redis:
    port: 6379
    password: foobared
    host: 192.168.206.130
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
logging:
  config: classpath:logback-spring.xml
server:
  port: 8080


