spring:
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #空值 不处理
    default-property-inclusion: non_null
    # DataSource Config
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.206.130:3306/security?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true
      connection-timeout: 30000
      max-lifetime: 120000
      connection-test-query: select 1
  redis:
    port: 6379
    password: foobared
    host: 192.168.206.130
logging:
  config: classpath:logback-spring.xml
server:
  port: 8080


